name: 'PR checks'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run coverage

      - name: Report Coverage
        if: ${{ github.event.pull_request }}
        uses: davelosert/vitest-coverage-report-action@v2
